module.exports = {
    TARGETED_MARKET: ['LOCAL', 'INTERNATIONAL', 'BOTH'],
    COMMERCIALISATION_TIMELINE: ['WITHIN_6_MONTHS', 'WITHIN_1_YEAR', 'BEYOND_1_YEAR'],
    EXPECTED_INVESTMENT: ['LESS_THAN_1_MIL', 'BETWEEN_1_AND_10_MIL', 'BETWEEN_10_AND_100_MIL', 'MORE_THAN_100_MIL'],
    TOTAL_REVENUE: ['LESS_THAN_1_MIL', 'BETWEEN_1_AND_10_MIL', 'BETWEEN_10_AND_100_MIL', 'MORE_THAN_100_MIL'],
    REGULATORY_APPROVAL: ['YES', 'NO'],
    LAND_REQUIREMENT: ['YES', 'NO'],
    APPROVAL_STATUS: ["PENDING", "APPROVED", "REJECTED", "UNDER_REVIEW", "IN_PROGRESS", "APPROVED_WITH_CONDITIONS", "NOT_REQUIRED", "WAITING_FOR_RESPONSE", "EXPIRED", "CANCELLED"]

};
